export const FETCH_USERS = "FETCH_USERS";
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const SAVE_QUESTION_ANSWER = "SAVE_QUESTION_ANSWER";
export const SAVE_NEW_QUESTION = "SAVE_NEW_QUESTION";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
